apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-webapp
  labels:
    app: image
spec:
  selector:
    matchLabels:
      app: image
  replicas: 3
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
      - name: sentiment-webapp
        image: sharmasonal/sentiment_webapp:latest
        ports:
        - containerPort: 8080
---
apiVersion:v1
kind:Service
metadata:
  name:sentiment-webapp
spec:
  selector:
    app: sentiment-webapp
  ports:
    - protocol: TCP 
      port: 8080 
      targetPort: 8080
      nodePort: 8080
  type: NodePort	